
server:
  port: 8769

spring:
  rabbitmq:
    host: anoax.com
    port: 5672
    username: anoax
    password: zhangan@28
  redis:
    database: 0
    host: anoax.com
    port: 6379
    password: zhangan@28
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  cache:
    type: REDIS
    cache-names: redis_cache , ehcache #缓存的名字
    redis:
      time-to-live: 60000  #很重要，缓存的有效时间，以便缓存的过期（单位为毫秒
  datasource:
    url: jdbc:mysql://anoax.com:3306/anoax?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: anoax
    password: zhangan@28
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    # Spring Cloud Eureka 注册中心地址
    service-url:
      #指定服务中心地址
      defaultZone: http://turbid:turbid321@localhost:8000/eureka/
    register-with-eureka: true
  instance:
    hostname: localhost
    #定义服务续约任务的调用间隔时间
    lease-renewal-interval-in-seconds: 30
    #定义服务失效时间
    lease-expiration-duration-in-seconds: 90
    #根路径
    home-page-url: http://${eureka.instance.hostname}/
    #状态页面
    status-page-url: http://${eureka.instance.hostname}/info
    #健康检查
    health-check-url: http://${eureka.instance.hostname}/health

security:
  oauth2:
    resource:
      jwt:
        key-value: auth.turbidexplore.com
management:  #actuator
  server:
    port: ${server.port}
  endpoints:
    web:
#      base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
#        include: refresh,health,info #打开部分

feign:
  compression:
    request:
      enabled: true #对请求进行压缩
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  hystrix:
    enabled: true
com:
  id: 123

